app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('', include('home.urls')),
    path('usersguid/', include('for_users.urls')),
    path('charactermaker/', include('charactermaker.urls')),

]

app/for_users/urls.py
from django.urls import path
from . import views


app_name = 'usersguid'

urlpatterns = [
    path('races/', views.races, name="races"),
    path('races/<race>/', views.show_race, name='race'),
    path('classes/', views.classes, name="classes"),
    path('classes/<classs>/', views.show_class, name='class'),
    path('personality/', views.personality, name="personality"),
    path('equipment/', views.equipment, name="equipment"),
    path('magic/', views.magic, name="magic"),
    path('magic/<class_id>', views.class_spells, name="class_spells"),
    path('usersguid/', views.usersguid, name="usersguid"),
    path('languages/', views.languages, name="languages")

]

app/templates/usersguid/race/race.html
{% extends 'base.html' %}

{% block title %}{{ context.race_name }}{% endblock %}

{% block content %}
{% load static %}

<div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
  <div class="flex items-center justify-between px-6 py-3">
    <h2 class="section-name text-gray">{{ context.race_name }}</h2>
    <p>{{ context.description }}</p>
    <div class="overflow-x-auto">
      {% csrf_token %}
      <img class="chapter-image" src="{% static  context.img_path %}">
      <div>
        <h4 class="race-features">Розмір : {{ context.size }}</h4>
        <h4 class="race-features">Тривалість життя : {{ context.max_age }}</h4>
        <h4 class="race-features">Швидкість : {{ context.speed }} футів</h4>
        <h4 class="race-features">Мови : {% for language in context.languages %} {{ language }}; {% endfor %}</h4>
        <h4 class="race-features">Збільшення характеристик :  </h4><h5>{% for bonus in context.race_bonus %} {{ bonus.name }} на {{ bonus.val }}, {% endfor %}</h5>
        <h4 class="race-features">Вміння : </h4>
        
        {% for trait in context.else_traits %}
        <h5 class="trait-name">{{ trait.name }}</h5>
        <p>{{ trait.value }}</p>
        {% endfor %}
      
      </div>
    </div>
    <div>
      {% for subrace in subraces %}
      <div class="subrace">
        {% if subrace.race_id == context.race_id %}
        <a href=#{{subrace.subrace_eng_name}}><h4> {{ subrace.subrace_name }} </h4></a>
        {% endif %}
      </div>
      {% endfor %}
    </div>
    <div class="info-chapter">
      {% for chapter in context.full_description %}
      <h3>{{ chapter.chapter_name }} </h3>
      <hr>
      <p> {{ chapter.chapter_value }} </p>
      {% endfor %}
    </div>
    <div>
      <div class="subrace">
        {% for subrace in subraces %}
        {% if subrace.race_id == context.race_id %}
        <hr>
        
        <h2 id={{subrace.subrace_eng_name}}> {{ subrace.subrace_name }} </h2>
        <div class="overflow-x-auto">
          <img class="chapter-image" src="{% static  subrace.img_path %}"></a>
          <div>
            <p> {{ subrace.subrace_description }} </p>
        <h4 class="race-features">Збільшення характеристик :  </h4><h5>{% for bonus in subrace.subrace_bonus %} {{ bonus.name }} на {{ bonus.val }}, {% endfor %}</h5>
          </div>
        </div>
        {% for trait in subrace.else_traits %}
        <h4>{{ trait.name }}</h4>
        <p>{{ trait.value }}</p>
        {% endfor %}
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/usersguid/race/races.html
{% extends 'base.html' %}

{% block title %}Site{% endblock %}

{% block content %}
{% load static %}

  <div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
    <div class="flex items-center justify-between px-6 py-3">
      <h2 class="section-name text-gray"> Раси </h2>
        <div class="classes overflow-x-auto">
          {% csrf_token %}
          {% for value in context %}
            <div class="one-class">
              <a href="{% url 'usersguid:race'  value.race_eng_name %}"> <img class="section-image" src="{% static  value.img_path %}" ></a>
              <a href="{% url 'usersguid:race'  value.race_eng_name %}"> <h3 class="race-title"> {{ value.race_name }} </h3> </a>
              <p class="description">
              {{ value.description }} </p>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>

{% endblock %}