app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('', include('home.urls')),
    path('usersguid/', include('for_users.urls')),
    path('charactermaker/', include('charactermaker.urls')),

]

app/for_users/urls.py
from django.urls import path
from . import views


app_name = 'usersguid'

urlpatterns = [
    path('races/', views.races, name="races"),
    path('races/<race>/', views.show_race, name='race'),
    path('classes/', views.classes, name="classes"),
    path('classes/<classs>/', views.show_class, name='class'),
    path('personality/', views.personality, name="personality"),
    path('equipment/', views.equipment, name="equipment"),
    path('magic/', views.magic, name="magic"),
    path('magic/<class_id>', views.class_spells, name="class_spells"),
    path('usersguid/', views.usersguid, name="usersguid"),
    path('languages/', views.languages, name="languages")

]

app/templates/usersguid/spells/class_spells.html
{% extends 'base.html' %}

{% block title %}Site{% endblock %}

{% block content %}
{% load static %}

<div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
  <div class="flex items-center justify-between px-6 py-3">
    <h2 class="section-name text-gray"> Заклинання {{ name }}ів </h2>
    <h4>{% if cantrips %} Заклинання 0-го рівня {% endif %}</h4>
    <div class="spells-popup">
    {% for spell in cantrips %}
    <!--    <div class="spell-block">-->
    <!--      <div class="spell_name">-->
    <!--        <h5>{{ spell.name }}</h5>-->
    <!--      </div>-->
    <!--      <div class="spell_description">-->
    <!--        <p class="spell-p">{{ spell.description }}</p>-->
    <!--      </div>-->
    <!--    </div>-->
      <div class="popup" onclick="myFunction()">{{ spell.name }}
        <span class="popuptext" id="myPopup">{{ spell.description }}</span>
      </div>
    {% endfor %}
    </div>

    <h4>{% if first %} Заклинання 1-го рівня {% endif %}</h4>
    {% for spell in first %}
    <div class="spell-block">
      <div class="spell_name">
        <h5>{{ spell.name }}</h5>
      </div>
      <div class="spell_description">
        <p class="spell-p">{{ spell.description }}</p>
      </div>
    </div>
    {% endfor %}


  </div>
</div>


<script>
  function myFunction() {
    var popup = document.getElementById("myPopup");
    popup.classList.toggle("show");
  }
</script>

{% endblock %}

app/templates/usersguid/spells/magic.html
{% extends 'base.html' %}

{% block title %}Site{% endblock %}

{% block content %}
{% load static %}

<div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
  <div class="flex items-center justify-between px-6 py-3">
    <div>
      <h2 class="section-name text-gray"> Заклинання </h2>
      <p> Магія пронизує світи фентезійних ігор і часто з’являється у формі заклинань. У цьому розділі містяться правила заклинань. Різні класи персонажів мають відмінні способи вивчення та підготовки заклинань, а монстри використовують заклинання унікальними способами. Незалежно від свого джерела, заклинання дотримується тут правил.</p>
      {% csrf_token %}

      <div class="class-spells">
        <a href="{% url 'usersguid:class_spells' 0%}"><h3 class="race-title"></h3> <h5>Всі</h5></a>
        <a href="{% url 'usersguid:class_spells' 1 %}"><h3 class="race-title"></h3> <h5>Артифактор</h5> </a>
        <a href="{% url 'usersguid:class_spells' 2 %}"><h3 class="race-title"></h3> <h5>Бард</h5> </a>
        <a href="{% url 'usersguid:class_spells' 5 %}"><h3 class="race-title"></h3> <h5>Друїд</h5> </a>
        <a href="{% url 'usersguid:class_spells' 6 %}"><h3 class="race-title"></h3> <h5>Клірик</h5> </a>
        <a href="{% url 'usersguid:class_spells' 8 %}"><h3 class="race-title"></h3> <h5>Паладин</h5> </a>
        <a href="{% url 'usersguid:class_spells' 9 %}"><h3 class="race-title"></h3> <h5>Рейнджер</h5> </a>
        <a href="{% url 'usersguid:class_spells' 11 %}"><h3 class="race-title"></h3> <h5>Чародій</h5> </a>
        <a href="{% url 'usersguid:class_spells' 12 %}"><h3 class="race-title"></h3> <h5>Чаклун</h5> </a>
        <a href="{% url 'usersguid:class_spells' 13 %}"><h3 class="race-title"></h3> <h5>Чарівник</h5> </a>
      </div>
      <div class="spelltext">
        <h3> Що таке заклинання? </h3>
        <p>Заклинання — це окремий магічний ефект, єдине формування магічних енергій, які наповнюють мультивсесвіт у конкретне, обмежене вираження. Виконуючи заклинання, персонаж обережно вищипує невидимі нитки сирої магії, що наповнюють світ, закріплює їх на місці в певному візерунку, налаштовує їх на певну вібрацію, а потім відпускає їх, щоб розв’язати бажаний ефект — у більшості випадків , і все це за лічені секунди.</p>
        <p>Заклинання можуть бути універсальними інструментами, зброєю або захисними вардами. Вони можуть завдавати шкоди або скасовувати її, накладати або знімати умови , висмоктувати життєву енергію та повертати життя мертвим.</p>
        <p>Незліченні тисячі заклинань були створені протягом історії мультивсесвіту, і багато з них давно забуті. Деякі ще можуть бути записані в книгах заклинань, що розпадаються , заховані в стародавніх руїнах або потрапили в уми мертвих богів. Або колись їх може переосмислити персонаж, який накопичив для цього достатньо сили та мудрості.</p>
        {% for value in section1 %}
        <h4>{{ value.title }}</h4>
        <hr>
        <p>{{ value.contents }}</p>
        {% endfor %}

        <h3>Як чаклувати?</h3>
        <p>Коли персонаж використовує будь-яке заклинання, дотримуються тих самих основних правил, незалежно від класу персонажа чи ефектів заклинання.</p>
        <p>Опис кожного заклинання починається з блоку інформації, включаючи назву заклинання, рівень, школу магії, час застосування, діапазон, компоненти та тривалість. Решта запису про заклинання описує ефект заклинання.</p>

        {% for value in section2 %}
        <h4>{{ value.title }}</h4>
        <hr>
        <p>{{ value.description }}</p>
        {% for item in value.contents %}
        <h5>{{ item.title }}</h5>
        <p>{{ item.contents }}</p>
        {% endfor %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}