app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('', include('home.urls')),
    path('usersguid/', include('for_users.urls')),
    path('charactermaker/', include('charactermaker.urls')),

]

app/for_users/urls.py
from django.urls import path
from . import views


app_name = 'usersguid'

urlpatterns = [
    path('races/', views.races, name="races"),
    path('races/<race>/', views.show_race, name='race'),
    path('classes/', views.classes, name="classes"),
    path('classes/<classs>/', views.show_class, name='class'),
    path('personality/', views.personality, name="personality"),
    path('equipment/', views.equipment, name="equipment"),
    path('magic/', views.magic, name="magic"),
    path('magic/<class_id>', views.class_spells, name="class_spells"),
    path('usersguid/', views.usersguid, name="usersguid"),
    path('languages/', views.languages, name="languages")

]

app/templates/usersguid/class/class.html
{% extends 'base.html' %}

{% block title %}{{ context.class_name }}{% endblock %}

{% block content %}
{% load static %}

<div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
  <div class="flex items-center justify-between px-6 py-3">
    <h2 class="section-name text-gray">{{ context.class_name }}</h2>
    <p>{{ context.description }}</p>
    <div class="overflow-x-auto">
      {% csrf_token %}
      <img class="chapter-image" src="{% static  context.img_path %}">
      <div class="class-text">
        <h5>Куби здоров'я: 1к{{ context.hit_dice }}</h5>
        <h5>Захисні кидки: {% for throw in context.saving_throws %} {{ throw }}; {% endfor %}</h5>
        <h5>Володіння</h5>
        
        {% for item in context.proficiencies %}
        
        {% if item.options and item.number != 0 %}
        <h6>{{ item.name }}: Оберіть {{ item.number }} з наданих варіантів:
          {% for i in item.options %} {{ i }}; {% endfor %}</h6>
        {% else %}
        <h6>{{ item.name }}: {% for i in item.value %} {{ i }}; {% endfor %}</h6>
        {% endif %}
        
        {% endfor %}
        <h5>Стартове спорядження</h5>
        {% for equip in context.start_equipment %}
        {% if equip.b %}
        <h6> а - {{ equip.a }};    б - {{ equip.b }};</h6>
        {% elif equip.a and equip.b and equip.c %}
        <h6> а - {{ equip.a }}; б - {{ equip.b }};  в - {{ equip.c }};</h6>
        {% else %}
        <h6>{{ equip.z }}</h6>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    <div>
      <h3>{{ context.subclass_naming }}</h3>
      {% for subclass in subclasses %}
      {% if subclass.class_id == context.class_id %}
      <div class="subrace">
        <a href=#{{subclass.eng_name}}><h4> {{ subclass.subclass_name }} </h4></a>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    {% for data in context.full_description %}
    <h5 class="trait-name">{{ data.chapter_name }}</h5>
    <hr>
    <p>{{ data.value }}</p>
    {% endfor %}
    <div class="info-chapter">
      <h3>Швидке створення</h3>
      <hr>
      <p>{{ context.advice }}</p>
    </div>
    <div class="subrace">
      
      {% for subclass in subclasses %}
      {% if subclass.class_id == context.class_id %}
      <hr>
      <h2 id={{subclass.eng_name}}> {{ subclass.subclass_name }} </h2>
      <div class="overflow-x-auto">
        <img class="chapter-image" src="{% static  subclass.img_path %}">
        <div>
        <p> {{ subclass.subclass_description }} </p>
        </div>
      </div>
          
          <h4> Навички </h4>
          {% for skill in subclass.subclass_skills %}
          <h5>{{ skill.skill_name }}</h5>
          <p>{{ skill.skill_description }}</p>
          {% for option in skill.options %}
          <h7>{{ option.name }}</h7>
          <p>{{ option.description }}</p>
          {% endfor %}
          {% endfor %}
      {% endif %}
      {% endfor %}
    
    
    </div>
  </div>
</div>

{% endblock %}

app/templates/usersguid/class/classes.html
{% extends 'base.html' %}

{% block title %}Site{% endblock %}

{% block content %}
{% load static %}

  <div class="2xl:container 2xl:mx-auto sm:py-5 sm:px-1 py-5 px-1">
    <div class="flex items-center justify-between px-6 py-3">
      <h2 class="section-name text-gray"> Класи </h2>
        <div class="classes overflow-x-auto">
          {% csrf_token %}
          {% for value in context %}
            <div class="one-class">
              <a href="{% url 'usersguid:class'  value.class_eng_name %}"> <img class="section-image" src="{% static  value.img_path %}" ></a>
              <a href="{% url 'usersguid:class'  value.class_eng_name %}"> <h3 class="race-title"> {{ value.class_name }} </h3> </a>
              <p class="description">
              {{ value.description }} </p>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>

{% endblock %}